### ISSUE TITLE
Strict Mode Violation With Shared Preferences

### ISSUE THREAD

**Issue by DavidTPate** [antew/RedditInPictures#143]
Receive the following stack trace:

```
com.antew.redditinpictures.pro D/StrictMode﹕ StrictMode policy violation; ~duration=91 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=2079 violation=2
            at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1074)
            at android.app.SharedPreferencesImpl.awaitLoadedLocked(SharedPreferencesImpl.java:184)
            at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:241)
            at com.antew.redditinpictures.library.preferences.SharedPreferencesHelper.getShowNsfwImages(SharedPreferencesHelper.java:254)
            at com.antew.redditinpictures.library.ui.RedditImageAdapterViewFragment.onCreateLoader(RedditImageAdapterViewFragment.java:252)
            at android.support.v4.app.LoaderManagerImpl.createLoader(LoaderManager.java:490)
            at android.support.v4.app.LoaderManagerImpl.createAndInstallLoader(LoaderManager.java:499)
            at android.support.v4.app.LoaderManagerImpl.restartLoader(LoaderManager.java:646)
            at com.antew.redditinpictures.library.ui.RedditImageAdapterViewFragment.onResume(RedditImageAdapterViewFragment.java:136)
            at android.support.v4.app.Fragment.performResume(Fragment.java:1543)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:974)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1115)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1097)
            at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:1905)
            at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:466)
            at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:455)
            at com.actionbarsherlock.app.SherlockFragmentActivity.onPostResume(SherlockFragmentActivity.java:68)
            at android.app.Activity.performResume(Activity.java:4552)
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2433)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2471)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1985)
            at android.app.ActivityThread.access$600(ActivityThread.java:122)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1146)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4340)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by DavidTPate** [comment]
Closing due to inactivity.
