### ISSUE TITLE
Strict Mode Violation With GZIP

### ISSUE THREAD

**Issue by DavidTPate** [antew/RedditInPictures#144]
Receive the following stack trace:

```
com.antew.redditinpictures.pro E/StrictMode﹕ A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'end' not called
            at dalvik.system.CloseGuard.open(CloseGuard.java:184)
            at java.util.zip.Inflater.<init>(Inflater.java:82)
            at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:96)
            at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:81)
            at com.antew.redditinpictures.library.service.RESTService$GzipDecompressingEntity.getContent(RESTService.java:356)
            at org.apache.http.conn.BasicManagedEntity.getContent(BasicManagedEntity.java:100)
            at org.apache.http.util.EntityUtils.toString(EntityUtils.java:112)
            at org.apache.http.util.EntityUtils.toString(EntityUtils.java:146)
            at com.antew.redditinpictures.library.service.RESTService.onHandleIntent(RESTService.java:185)
            at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.os.HandlerThread.run(HandlerThread.java:60)
```

**Comment by DavidTPate** [comment]
Closing due to inactivity.
