### ISSUE TITLE
Crash on Nexus S (emulator)

### ISSUE THREAD

**Issue by DavidTPate** [antew/RedditInPictures#145]
Receive the following crash on the Nexus S emulator Android 2.3.3 (API 10) when switching to "Top: Hour" on any subreddit.

```
com.antew.redditinpictures.pro E/AndroidRuntime﹕ FATAL EXCEPTION: IntentService[RESTService]
    java.lang.NullPointerException
            at com.antew.redditinpictures.library.model.reddit.RedditApi.getContentValues(RedditApi.java:125)
            at com.antew.redditinpictures.library.reddit.PostResponse.processHttpResponse(PostResponse.java:66)
            at com.antew.redditinpictures.library.reddit.RedditResult.handleResponse(RedditResult.java:18)
            at com.antew.redditinpictures.library.service.RedditService.onRequestComplete(RedditService.java:260)
            at com.antew.redditinpictures.library.service.RESTService.onHandleIntent(RESTService.java:190)
            at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:59)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:123)
            at android.os.HandlerThread.run(HandlerThread.java:60)
```

**Comment by DavidTPate** [comment]
Got the same crash on the Galaxy Nexus Android 4.0.2 (API 14).
