### ISSUE TITLE
Strict Mode Violation With WebView

### ISSUE THREAD

**Issue by DavidTPate** [antew/RedditInPictures#150]
While testing on the Galaxy Nexus Android 4.0.2 (API 14) and attempting to view a GIF the following stack trace occurred:

```
com.antew.redditinpictures.pro E/StrictMode﹕ null
    java.lang.Throwable: Warning: A WebView method was called on thread 'WebViewCoreThread'. All WebView methods must be called on the UI thread. Future versions of WebView may not support use on other threads.
            at android.webkit.WebView.checkThread(WebView.java:9355)
            at android.webkit.WebView.getSettings(WebView.java:4053)
            at android.webkit.ZoomManager.getReadingLevelScale(ZoomManager.java:317)
            at android.webkit.WebView.getReadingLevelScale(WebView.java:2448)
            at android.webkit.WebViewCore.setupViewport(WebViewCore.java:2487)
            at android.webkit.WebViewCore.didFirstLayout(WebViewCore.java:2258)
            at android.webkit.JWebCoreJavaBridge.sharedTimerFired(Native Method)
            at android.webkit.JWebCoreJavaBridge.fireSharedTimer(JWebCoreJavaBridge.java:93)
            at android.webkit.JWebCoreJavaBridge.handleMessage(JWebCoreJavaBridge.java:110)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.webkit.WebViewCore$WebCoreThread.run(WebViewCore.java:722)
            at java.lang.Thread.run(Thread.java:856)
```

**Comment by DavidTPate** [comment]
Closing due to inactivity.
