### ISSUE TITLE
Crash when switching between GridView and ListView

### ISSUE THREAD

**Issue by antew** [antew/RedditInPictures#69]
Let the app load some images (don't scroll), switch to the GridView, scroll all the way to the bottom, let new images load, and then try switching back to the ListView.

On my Galaxy Nexus running cyanogen 10.2.1 (toro) I get this stack trace:

```
03-03 20:15:12.478  16726-16726/com.antew.redditinpictures.pro E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteQuery: SELECT _id, url, thumbnail, title, score, selfText, numComments, subreddit, domain, author, vote, name, over18 FROM post_data ORDER BY _id ASC
            at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
            at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:58)
            at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:152)
            at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:124)
            at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:214)
            at android.database.CursorWrapper.moveToPosition(CursorWrapper.java:162)
            at android.support.v4.widget.CursorAdapter.getView(CursorAdapter.java:247)
            at android.widget.AbsListView.obtainView(AbsListView.java:2177)
            at android.widget.ListView.makeAndAddView(ListView.java:1840)
            at android.widget.ListView.fillSpecific(ListView.java:1321)
            at android.widget.ListView.layoutChildren(ListView.java:1645)
            at android.widget.AbsListView.onLayout(AbsListView.java:2012)
            at android.view.View.layout(View.java:14296)
            at android.view.ViewGroup.layout(ViewGroup.java:4562)
            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
            at android.view.View.layout(View.java:14296)
            at android.view.ViewGroup.layout(ViewGroup.java:4562)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
            at android.view.View.layout(View.java:14296)
            at android.view.ViewGroup.layout(ViewGroup.java:4562)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
            at android.view.View.layout(View.java:14296)
            at android.view.ViewGroup.layout(ViewGroup.java:4562)
            at net.simonvt.menudrawer.OverlayDrawer.onLayout(OverlayDrawer.java:258)
            at android.view.View.layout(View.java:14296)
            at android.view.ViewGroup.layout(ViewGroup.java:4562)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
            at android.view.View.layout(View.java:14296)
            at android.view.ViewGroup.layout(ViewGroup.java:4562)
            at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:349)
            at android.view.View.layout(View.java:14296)
            at android.view.ViewGroup.layout(ViewGroup.java:4562)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
            at android.view.View.layout(View.java:14296)
            at android.view.ViewGroup.layout(ViewGroup.java:4562)
            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1976)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1730)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1004)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5481)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
            at android.view.Choreographer.doCallbacks(Choreographer.java:562)
            at android.view.Choreographer.doFrame(Choreographer.java:532)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
            at android.os.Handler.handleCallback(Handler.java:730)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5289)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by antew** [comment]
Almost have this one tackled.
